name: Checks & Tests

on:
  workflow_call:
  pull_request:
    branches:
      - main
      - dev

jobs:
  check:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun check
      - run: bun test
